In [2]:
import pandas as pd
import numpy as np

In [3]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 7C66-8E97

 Directory of C:\Users\ch186802\Python\Test

06/15/2018  13:45    <DIR>          .
06/15/2018  13:45    <DIR>          ..
06/15/2018  13:39    <DIR>          .ipynb_checkpoints
06/15/2018  13:45               753 Untitled.ipynb
08/11/2016  14:07         3,714,254 yesware-test-data-v1-6.txt
               2 File(s)      3,715,007 bytes
               3 Dir(s)  314,275,565,568 bytes free

In [13]:
raw_data = pd.read_table('yesware-test-data-v1-6.txt', names=('A'))

In [21]:
df = pd.DataFrame(raw_data)
df.columns=['original']

In [26]:
df['split'] = df['original'].split('--')

AttributeError: 'Series' object has no attribute 'split'

In [28]:
# below line parses the entire df, removes everything after the '--' & writes data to a new column called split
df['split'] = df['original'].map(lambda x: x.split('--', 1)[0])

In [31]:
# below line displays only every 2nd row in the df
df.iloc[::2]

                                original                  split
0                  Graham, Mckenna -- ut       Graham, Mckenna
2                Marvin, Garfield -- non      Marvin, Garfield
4      McLaughlin, Mariah -- consequatur    McLaughlin, Mariah
6             Lang, Agustina -- pariatur        Lang, Agustina
8                   Bradtke, Nikko -- et        Bradtke, Nikko
10                  Adams, Luis -- error           Adams, Luis
12           Lehner, Matilde -- nesciunt       Lehner, Matilde
14                  Ortiz, Anita -- fuga          Ortiz, Anita
16                    Koch, Berry -- vel           Koch, Berry
18             Cartwright, Nicolas -- et   Cartwright, Nicolas
20                   Fisher, Elmo -- non          Fisher, Elmo
22         Kunze, Gertrude -- voluptatem       Kunze, Gertrude
24               Stanton, Davin -- porro        Stanton, Davin
26     O'Conner, Constantin -- veritatis  O'Conner, Constantin
28              Runolfsdottir, Roy -- et    Runolfsdottir, Roy
30             Rogahn, Colby -- quisquam         Rogahn, Colby
32                   Tromp, Ryley -- est          Tromp, Ryley
34                 Hoppe, Stanley -- est        Hoppe, Stanley
36             Shanahan, Bethel -- rerum      Shanahan, Bethel
38                 Hills, Samanta -- aut        Hills, Samanta
40                  McGlynn, Thad -- sed         McGlynn, Thad
42              McGlynn, Katrina -- quia      McGlynn, Katrina
44              Lynch, Norma -- expedita          Lynch, Norma
46          Bahringer, Lennie -- aliquam     Bahringer, Lennie
48       Tillman, Madison -- praesentium      Tillman, Madison
50         Stoltenberg, Donna -- ratione    Stoltenberg, Donna
52        Dickinson, Sonya -- asperiores      Dickinson, Sonya
54             Bechtelar, Jane -- magnam       Bechtelar, Jane
56               Graham, Alfonzo -- quas       Graham, Alfonzo
58        McDermott, Ivah -- consequatur       McDermott, Ivah
...                                  ...                    ...
99940          Schneider, Everette -- id   Schneider, Everette
99942      Roberts, Holden -- reiciendis       Roberts, Holden
99944             Jast, Gail -- expedita            Jast, Gail
99946        Witting, Trenton -- debitis      Witting, Trenton
99948             Goodwin, Zetta -- eius        Goodwin, Zetta
99950          Ratke, Kaleb -- molestiae          Ratke, Kaleb
99952          Brakus, Emilia -- aliquid        Brakus, Emilia
99954         Rippin, Jose -- voluptatem          Rippin, Jose
99956    Keebler, Forrest -- accusantium      Keebler, Forrest
99958           Rohan, Hellen -- aperiam         Rohan, Hellen
99960       Schuster, Arden -- excepturi       Schuster, Arden
99962       Schneider, Kayley -- facilis     Schneider, Kayley
99964       Buckridge, Cassidy -- itaque    Buckridge, Cassidy
99966  Emmerich, Loraine -- consequuntur     Emmerich, Loraine
99968      Johnston, Kevin -- blanditiis       Johnston, Kevin
99970             Kirlin, Kylee -- natus         Kirlin, Kylee
99972             Pouros, Kellie -- iure        Pouros, Kellie
99974        Mosciski, Stephania -- quia   Mosciski, Stephania
99976             Emmerich, Hubert -- et      Emmerich, Hubert
99978                Kris, Devon -- quas           Kris, Devon
99980               Heller, Sadie -- eos         Heller, Sadie
99982            Beatty, Bertha -- omnis        Beatty, Bertha
99984       Pollich, Richie -- voluptate       Pollich, Richie
99986             Feil, Louie -- facilis           Feil, Louie
99988        Jones, Elyssa -- voluptatum         Jones, Elyssa
99990            Kuhlman, Demarco -- est      Kuhlman, Demarco
99992     MacGyver, Fabian -- aspernatur      MacGyver, Fabian
99994             Wehner, Keyshawn -- et      Wehner, Keyshawn
99996             Littel, Joel -- labore          Littel, Joel
99998             Hettinger, Brett -- in      Hettinger, Brett

[50000 rows x 2 columns]